language: python
python: 2.7
cache: pip
sudo: true
dist: xenial
services:
  - postgresql
  - rabbitmq
addons:
  apt:
    packages:
      - rabbitmq-server
      - python3
      - python3-tk
      - python3-pip
      - python3-numpy
      - python3-scipy
      - python3-h5py
      - python3-matplotlib
  postgresql: "9.5"
before_install:
  - sudo pip3 install -U setuptools
  - sudo pip3 install git+https://github.com/Z2PackDev/bands_inspect.git#egg=bands-inspect
  - sudo pip3 install git+https://github.com/Z2PackDev/TBmodels.git@dev#egg=tbmodels
install:
  - pip install -U pip wheel setuptools
  - pip install git+https://github.com/aiidateam/aiida_core.git#egg=aiida_core
  - pip install git+https://github.com/greschd/aiida_pytest@develop#egg=aiida_pytest
  - pip install git+https://github.com/greschd/aiida-bands-inspect.git#egg=aiida-bands-inspect
  - pip install .[dev]
env:
  - TEST_TYPE="pre-commit"
  - TEST_TYPE="tests"
script:
  - ./.travis-data/test_script.sh
