language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
services:
  - postgresql
  - rabbitmq
addons:
  apt:
    packages:
      - rabbitmq-server
      - python3
      - python3-tk
      - python3-pip
      - python3-h5py
      - python3-matplotlib
before_install:
  - pip install -U pip setuptools
  - pip install -U numpy scipy python-dateutil
  - pip install -U bands-inspect
  - pip install -U git+https://github.com/Z2PackDev/TBmodels.git@dev
  - sudo service postgresql restart
install:
  - pip install -U 'pip<19' wheel setuptools
  - pip install .[dev]
  - reentry scan
env:
  - TEST_TYPE="pre-commit"
  - TEST_TYPE="tests"
script:
  - ./.travis-data/test_script.sh
