computers:
  localhost:
    hostname: localhost
    description: localhost
    transport: local
    scheduler: direct
    work_directory: /tmp/test_aiida_tbmodels_run

codes:
  tbmodels:
    description: tbmodels
    default_plugin: tbmodels.parse
    remote_computer: localhost
    remote_abspath: {tbmodels_path}

  bands_inspect:
    description: bands_inspect
    default_plugin: bands_inspect.difference
    remote_computer: localhost
    remote_abspath: {bands_inspect_path}
